from django.urls import path
from mypupqc.views import SchedulerAuthView, UsersView
from mypupqc.controller import *

urlpatterns = [
    # Authentication Paths
    path(
        "authentication/Login/",
        SchedulerAuthView.as_view(template_name="sysAdmin/authentication/sysAdmin_login.html"),
        name="sysAdminLogin",
    ),
    path(
        'authentication/Login/LoginSysAdmin/', 
        AuthController.showSysAdminLogin, 
        name='sysAdminLogin.Post',
    ),
    path(
        'authentication/Login/LogoutSysAdmin/', 
        AuthController.sysAdminLogout, 
        name='sysAdminLogout',
    ),
    path(
        "authentication/ForgotPassword/",
        SchedulerAuthView.as_view(template_name="sysAdmin/authentication/sysAdmin_forgot-password.html"),
        name="sysAdminForgotPassword",
    ),

    # Create Admin URL
    path("create-admin/<str:email>/<str:accessString>/", SysAdminController.initAdmin, name="SAcreateAdmin"),

    # Main Pages
    path(
        "Admin/Homepage/",
        UsersView.as_view(template_name="sysAdmin/Admin/sysAdmin_Homepage.html"),
        name="sysAdminHomepage",
    ),
    path(
        "Admin/editSysAdminProfile/",
        SysAdminController.editSysAdminProfile,
        name="editSysAdminProfile",
    ),

    path(
        "Admin/Account-Management/",
        UsersView.as_view(template_name="sysAdmin/Admin/sysAdmin_Account-Management.html"),
        name="sysAdminAccountManagement",
    ),
    path(
        "Admin/Account-Management/Manage-program/",
        UsersView.as_view(template_name="sysAdmin/Admin/Account-Management/AMmanage-program.html"),
        name="sysAdminManageProgram",
    ),
    path(
        "Admin/Account-Management/Manage-Bulk-Upload/",
        UsersView.as_view(template_name="sysAdmin/Admin/Account-Management/AMmanage-bulk_upload.html"),
        name="sysAdminManageBulkUpload",
    ),
    path(
        "Admin/Account-Management/Manage-Recycle/",
        UsersView.as_view(template_name="sysAdmin/Admin/Account-Management/AMmanage-recycle_account.html"),
        name="sysAdminManageRecycle",
    ),
    path(
        "Admin/Account-Management/getActiveProgram/",
        SysAdminController.getActiveProgram,
        name="getActiveProgram",
    ),
    path(
        "Admin/Account-Management/getStudentAlumniFilterOptions/",
        SysAdminController.getStudentAlumniFilterOptions,
        name="getStudentAlumniFilterOptions",
    ),
    path(
        "Admin/Account-Management/getSpecificUser/",
        SysAdminController.getSpecificUser,
        name="getSpecificUser",
    ),
    path(
        "Admin/Account-Management/getStudentList/",
        SysAdminController.getStudentList,
        name="getStudentList",
    ),
    path(
        "Admin/Account-Management/getPermissionList/",
        SysAdminController.getPermissionList,
        name="getPermissionList",
    ),
    path(
        "Admin/Account-Management/transferStudent/",
        SysAdminController.transferStudent,
        name="transferStudent",
    ),
    path(
        "Admin/Account-Management/batchTransferStudent/",
        SysAdminController.batchTransferStudent,
        name="batchTransferStudent",
    ),
    path(
        "Admin/Account-Management/addStudent/",
        SysAdminController.addStudent,
        name="addStudent",
    ),
    path(
        "Admin/Account-Management/editStudent/",
        SysAdminController.editStudent,
        name="editStudent",
    ),
    path(
        "Admin/Account-Management/deleteStudent/",
        SysAdminController.deleteStudent,
        name="deleteStudent",
    ),
    path(
        "Admin/Account-Management/batchDeleteStudent/",
        SysAdminController.batchDeleteStudent,
        name="batchDeleteStudent",
    ),
    path(
        "Admin/Account-Management/addAlumni/",
        SysAdminController.addAlumni,
        name="addAlumni",
    ),
    path(
        "Admin/Account-Management/editAlumni/",
        SysAdminController.editAlumni,
        name="editAlumni",
    ),
    path(
        "Admin/Account-Management/getFacultyList/",
        SysAdminController.getFacultyList,
        name="getFacultyList",
    ),
    path(
        "Admin/Account-Management/getSpecificFacultyRoles/",
        SysAdminController.getSpecificFacultyRoles,
        name="getSpecificFacultyRoles",
    ),
    path(
        "Admin/Account-Management/editFacultyRoles/",
        SysAdminController.editFacultyRoles,
        name="editFacultyRoles",
    ),
    path(
        "Admin/Account-Management/deleteFaculty/",
        SysAdminController.deleteFaculty,
        name="deleteFaculty",
    ),
    path(
        "Admin/Account-Management/batchDeleteFaculty/",
        SysAdminController.batchDeleteFaculty,
        name="batchDeleteFaculty",
    ),
    path(
        "Admin/Account-Management/getPersonnelList/",
        SysAdminController.getPersonnelList,
        name="getPersonnelList",
    ),
    path(
        "Admin/Account-Management/addPersonnel/",
        SysAdminController.addPersonnel,
        name="addPersonnel",
    ),
    path(
        "Admin/Account-Management/editPersonnel/",
        SysAdminController.editPersonnel,
        name="editPersonnel",
    ),
    path(
        "Admin/Account-Management/getSpecificPersonnelRoles/",
        SysAdminController.getSpecificPersonnelRoles,
        name="getSpecificPersonnelRoles",
    ),
    path(
        "Admin/Account-Management/editPersonnelRoles/",
        SysAdminController.editPersonnelRoles,
        name="editPersonnelRoles",
    ),
    path(
        "Admin/Account-Management/deletePersonnel/",
        SysAdminController.deletePersonnel,
        name="deletePersonnel",
    ),
    path(
        "Admin/Account-Management/batchDeletePersonnel/",
        SysAdminController.batchDeletePersonnel,
        name="batchDeletePersonnel",
    ),
    path(
        "Admin/Account-Management/Manage-Programs/getActiveProgram/",
        SysAdminController.getActiveProgram,
        name="getActiveProgram",
    ),
    path(
        "Admin/Account-Management/Manage-Programs/getSpecificProgram/",
        SysAdminController.getSpecificProgram,
        name="getSpecificProgram",
    ),
    path(
        "Admin/Account-Management/Manage-Programs/addProgram/",
        SysAdminController.addProgram,
        name="addProgram",
    ),
    path(
        "Admin/Account-Management/Manage-Programs/editProgram/",
        SysAdminController.editProgram,
        name="editProgram",
    ),
    path(
        "Admin/Account-Management/Manage-Programs/deleteProgram/",
        SysAdminController.deleteProgram,
        name="deleteProgram",
    ),
    path(
        "Admin/Account-Management/Manage-Programs/bulkDeleteProgram/",
        SysAdminController.bulkDeleteProgram,
        name="bulkDeleteProgram",
    ),
    path(
        "Admin/Account-Management/Manage-Recycle-Account/getRetainedAccounts/",
        SysAdminController.getRetainedAccounts,
        name="getRetainedAccounts",
    ),
    path(
        "Admin/Account-Management/Manage-Recycle-Account/deleteRetainedAccount/",
        SysAdminController.deleteRetainedAccount,
        name="deleteRetainedAccount",
    ),
    path(
        "Admin/Account-Management/Manage-Recycle-Account/bulkDeleteRetainedAccounts/",
        SysAdminController.bulkDeleteRetainedAccounts,
        name="bulkDeleteRetainedAccounts",
    ),
    path(
        "Admin/Account-Management/Manage-Recycle-Account/reactivateRetainedAccount/",
        SysAdminController.reactivateRetainedAccount,
        name="reactivateRetainedAccount",
    ),
    path(
        "Admin/Account-Management/Manage-Recycle-Account/bulkReactivateRetainedAccounts/",
        SysAdminController.bulkReactivateRetainedAccounts,
        name="bulkReactivateRetainedAccounts",
    ),
    path(
        "Admin/Account-Management/Manage-Recycle-Account/bulkReactivateRetainedAccounts/",
        SysAdminController.bulkReactivateRetainedAccounts,
        name="bulkReactivateRetainedAccounts",
    ),
    path(
        "Admin/Account-Management/Manage-Bulk-Upload/getPendingAccounts/",
        SysAdminController.getPendingAccounts,
        name="getPendingAccounts",
    ),
    path(
        "Admin/Account-Management/Manage-Bulk-Upload/getSpecificPendingAccount/",
        SysAdminController.getSpecificPendingAccount,
        name="getSpecificPendingAccount",
    ),
    path(
        "Admin/Account-Management/Manage-Bulk-Upload/activateUploadedAccount/",
        SysAdminController.activateUploadedAccount,
        name="activateUploadedAccount",
    ),
    path(
        "Admin/Account-Management/Manage-Bulk-Upload/bulkActivateUploadedAccount/",
        SysAdminController.bulkActivateUploadedAccount,
        name="bulkActivateUploadedAccount",
    ),
    path(
        "Admin/Account-Management/Manage-Bulk-Upload/editBulkUploadAccount/",
        SysAdminController.editBulkUploadAccount,
        name="editBulkUploadAccount",
    ),
    path(
        "Admin/Account-Management/Manage-Bulk-Upload/deleteBulkUploadAccount/",
        SysAdminController.deleteBulkUploadAccount,
        name="deleteBulkUploadAccount",
    ),
    path(
        "Admin/Account-Management/Manage-Bulk-Upload/bulkDeleteBulkUploadAccounts/",
        SysAdminController.bulkDeleteBulkUploadAccounts,
        name="bulkDeleteBulkUploadAccounts",
    ),
    path(
        "Admin/Account-Management/Manage-Bulk-Upload/processBulkUploads/",
        SysAdminController.processBulkUploads,
        name="processBulkUploads",
    ),
    path(
        "Admin/Audit/getHistoryLogs/",
        SysAdminController.getHistoryLogs,
        name="getHistoryLogs",
    ),

    path(
        "Admin/Content-Management/getMainSlideShows/",
        SysAdminController.getMainSlideShows,
        name="getMainSlideShows",
    ),
    path(
        "Admin/Content-Management/getMyPUPQCSlideShows/",
        SysAdminController.getMyPUPQCSlideShows,
        name="getMyPUPQCSlideShows",
    ),
    path(
        "Admin/Content-Management/addSlideShow/",
        SysAdminController.addSlideShow,
        name="addSlideShow",
    ),
    path(
        "Admin/Content-Management/editSlideShow/",
        SysAdminController.editSlideShow,
        name="editSlideShow",
    ),
    path(
        "Admin/Content-Management/deleteSlideShow/",
        SysAdminController.deleteSlideShow,
        name="deleteSlideShow",
    ),
    path(
        "Admin/Content-Management/bulkDeleteSlideShow/",
        SysAdminController.bulkDeleteSlideShow,
        name="bulkDeleteSlideShow",
    ),

    path(
        "Admin/Content-Management/getArticles/",
        SysAdminController.getArticles,
        name="getArticles",
    ),
    path(
        "Admin/Content-Management/getSpecificArticle/",
        SysAdminController.getSpecificArticle,
        name="getSpecificArticle",
    ),
    path(
        "Admin/Content-Management/addArticle/",
        SysAdminController.addArticle,
        name="addArticle",
    ),
    path(
        "Admin/Content-Management/editArticle/",
        SysAdminController.editArticle,
        name="editArticle",
    ),
    path(
        "Admin/Content-Management/deleteArticle/",
        SysAdminController.deleteArticle,
        name="deleteArticle",
    ),
    path(
        "Admin/Content-Management/bulkDeleteArticle/",
        SysAdminController.bulkDeleteArticle,
        name="bulkDeleteArticle",
    ),

    path(
        "Admin/Content-Management/getFAQs/",
        SysAdminController.getFAQs,
        name="getFAQs",
    ),
    path(
        "Admin/Content-Management/getSpecificFAQ/",
        SysAdminController.getSpecificFAQ,
        name="getSpecificFAQ",
    ),
    path(
        "Admin/Content-Management/addFAQ/",
        SysAdminController.addFAQ,
        name="addFAQ",
    ),
    path(
        "Admin/Content-Management/editFAQ/",
        SysAdminController.editFAQ,
        name="editFAQ",
    ),
    path(
        "Admin/Content-Management/deleteFAQ/",
        SysAdminController.deleteFAQ,
        name="deleteFAQ",
    ),
    path(
        "Admin/Content-Management/bulkDeleteFAQ/",
        SysAdminController.bulkDeleteFAQ,
        name="bulkDeleteFAQ",
    ),

    path(
        "Admin/Content-Management/getHowTo/",
        SysAdminController.getHowTo,
        name="getHowTo",
    ),
    path(
        "Admin/Content-Management/addHowTo/",
        SysAdminController.addHowTo,
        name="addHowTo",
    ),
    path(
        "Admin/Content-Management/editHowTo/",
        SysAdminController.editHowTo,
        name="editHowTo",
    ),
    path(
        "Admin/Content-Management/deleteHowTo/",
        SysAdminController.deleteHowTo,
        name="deleteHowTo",
    ),
    path(
        "Admin/Content-Management/bulkDeleteHowTo/",
        SysAdminController.bulkDeleteHowTo,
        name="bulkDeleteHowTo",
    ),

    path(
        "Admin/Content-Management/",
        UsersView.as_view(template_name="sysAdmin/Admin/sysAdmin_Content-Management.html"),
        name="sysAdminContentManagement",
    ),
    path(
        "Admin/Audit/",
        UsersView.as_view(template_name="sysAdmin/Admin/sysAdmin_Audit.html"),
        name="sysAdminAudit",
    ),

    # System Admin Profile Paths
    path(
        "Admin/Profile/",
        UsersView.as_view(template_name="sysAdmin/Admin/Settings/sysAdmin_Profile.html"),
        name="sysAdmin-Profile-Page",
    ),
    path(
        "Admin/Security",
        UsersView.as_view(template_name="sysAdmin/Admin/Settings/sysAdmin_Security.html"),
        name="sysAdmin-Security-Page",
    ),
]

# Dashboard Get URLS
urlpatterns += [
    path(
        "Admin/Dashboard/getCardsInformation/",
        SysAdminDashboardController.getCardsInformation,
        name="getCardsInformation",
    ),
    path(
        "Admin/Dashboard/getTotalRegisteredUsers/",
        SysAdminDashboardController.getTotalRegisteredUsers,
        name="getTotalRegisteredUsers",
    ),
    path(
        "Admin/Dashboard/getLatestRegisteredUsers/",
        SysAdminDashboardController.getLatestRegisteredUsers,
        name="getLatestRegisteredUsers",
    ),
    path(
        "Admin/Dashboard/getTotalStudentsPerProgram/",
        SysAdminDashboardController.getTotalStudentsPerProgram,
        name="getTotalStudentsPerProgram",
    ),
    path(
        "Admin/Dashboard/getTotalRegisteredUsersPerYear/",
        SysAdminDashboardController.getTotalRegisteredUsersPerYear,
        name="getTotalRegisteredUsersPerYear",
    ),
]
