# Generated by Django 5.0 on 2025-05-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPUPQC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbotdata',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
