# Generated by Django 5.0 on 2025-06-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myPUPQC', '0002_chatbotdata_extracted_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotLabel',
            fields=[
                ('label_id', models.AutoField(primary_key=True, serialize=False)),
                ('label_name', models.CharField(max_length=255)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
