# Generated by Django 5.1.7 on 2025-03-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypupqc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobileNo',
            field=models.CharField(max_length=16),
        ),
    ]
