# Generated by Django 5.1.7 on 2025-03-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypupqc', '0002_alter_student_mobileno'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='remarks',
            field=models.TextField(null=True),
        ),
    ]
