# Generated by Django 5.1.7 on 2025-03-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypupqc', '0005_slideshow_status_alter_postimages_imagelink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlessection',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='articlessection',
            name='startDate',
            field=models.DateField(null=True),
        ),
    ]
