# Generated by Django 5.1.7 on 2025-03-13 13:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypupqc', '0006_articlessection_enddate_articlessection_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlessection',
            name='articleImage',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
