# Generated by Django 5.1.7 on 2025-03-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypupqc', '0009_frequentlyaskedquestions_statis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequentlyaskedquestions',
            old_name='statis',
            new_name='status',
        ),
    ]
