# Generated by Django 5.1.7 on 2025-03-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypupqc', '0010_rename_statis_frequentlyaskedquestions_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='howtolinks',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
