# Generated by Django 5.1.7 on 2025-03-15 02:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypupqc', '0011_howtolinks_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chikas',
            name='chikaImage',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
