# Generated by Django 5.1.7 on 2025-03-15 10:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypupqc', '0012_alter_chikas_chikaimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReportFlags',
            fields=[
                ('reportID', models.AutoField(primary_key=True, serialize=False)),
                ('reportDescription', models.TextField()),
                ('reportCategory', models.CharField(max_length=50)),
                ('createdTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedTime', models.DateTimeField(null=True)),
                ('isActive', models.IntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='flagReasons',
            field=models.ForeignKey(db_column='flagReasons', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mypupqc.postreportflags'),
        ),
    ]
