# Generated by Django 5.1.7 on 2025-03-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypupqc', '0015_chikas_enddate_chikas_startdate_chikas_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendarevents',
            old_name='eventDate',
            new_name='eventStartDate',
        ),
        migrations.AddField(
            model_name='calendarevents',
            name='eventEndDate',
            field=models.DateField(default='2025-03-31'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calendarevents',
            name='eventUrl',
            field=models.TextField(null=True),
        ),
    ]
