# Generated by Django 5.1.7 on 2025-03-16 04:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypupqc', '0016_rename_eventdate_calendarevents_eventstartdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevents',
            name='updatedTime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
