# Generated by Django 5.1.7 on 2025-03-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypupqc', '0017_alter_calendarevents_updatedtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='mobileNo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pendingaccount',
            name='mobileNo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='mobileNo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobileNo',
            field=models.CharField(max_length=20),
        ),
    ]
