# Generated by Django 5.1.7 on 2025-03-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypupqc', '0003_personnel_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='mobileNo',
            field=models.CharField(default='', max_length=11),
            preserve_default=False,
        ),
    ]
