# Generated by Django 5.1.7 on 2025-03-13 06:20

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypupqc', '0004_personnel_mobileno'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='status',
            field=models.CharField(default='Active', max_length=10),
        ),
        migrations.AlterField(
            model_name='postimages',
            name='imageLink',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
