# Generated by Django 5.1.7 on 2025-03-13 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypupqc', '0007_alter_articlessection_articleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlessection',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
