# Generated by Django 5.1.7 on 2025-03-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypupqc', '0008_articlessection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentlyaskedquestions',
            name='statis',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
