# Generated by Django 5.1.7 on 2025-03-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypupqc', '0013_postreportflags_alter_post_flagreasons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='flagReasons',
            new_name='reportID',
        ),
        migrations.AddField(
            model_name='postreportflags',
            name='reportTitle',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
