# Generated by Django 5.1.7 on 2025-03-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypupqc', '0014_rename_flagreasons_post_reportid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chikas',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='chikas',
            name='startDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='chikas',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
